### ISSUE TITLE
nullpointer on bitmap

### ISSUE THREAD

**Issue by AhmedX6** [nisrulz/screenshott#18]
Hello,

Facing an issue on Nougat (Android 7.0)

 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createBitmap(Bitmap.java:773)
        at github.nisrulz.screenshott.ScreenShott.takeScreenShotOfView(ScreenShott.java:74)

Please any help.
It's ok on 5.0 and 8.0+ but in 7.0 I have crash

any help please ?

Thanks

**Comment by MoustafaElsaghier** [comment]
any solution?

**Comment by Fregionz** [comment]
i got this problem also, anyone have solutions?

Catch msg: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object references

**Comment by nisrulz** [comment]
This doesn't seem to be coming from any manipulation the library does, rather it is being thrown at [line 74](https://github.com/nisrulz/screenshott/blob/master/screenshott/src/main/java/github/nisrulz/screenshott/ScreenShott.java#L74)

i.e `Bitmap.createBitmap(v.getDrawingCache())`

From what I understand, it is happening due to not enough memory. 
Found a SO answer for the same: https://stackoverflow.com/a/40623623/2745762

I could downscale the image in such a situation by catching this error.
